const FIND_ALL_TASKS = 'FIND_ALL_TASKS';
const ADD_TASK = 'ADD_TASK';
const UPDATE_TASK = 'UPDATE_TASK';
const REMOVE_TASK = 'REMOVE_TASK';
const TASK_ACTION_ERROR = 'TASK_ACTION_ERROR';
const SELECT_TASK = 'SELECT_TASK';

export {FIND_ALL_TASKS, ADD_TASK, UPDATE_TASK, REMOVE_TASK, TASK_ACTION_ERROR, SELECT_TASK}