const FIND_ALL_TASKS = 'FIND_ALL_TASKS';
const ADD_TASK = 'ADD_TASK';
const UPDATE_TASK = 'UPDATE_TASK';
const REMOVE_TASK = 'REMOVE_TASK';

export { FIND_ALL_TASKS, ADD_TASK, UPDATE_TASK, REMOVE_TASK }